spring:
  application:
    name: Feature Service

  datasource:
    url: jdbc:postgresql://localhost:5435/feature-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
