spring:
  application:
    name: Team Api
  datasource:
    url: jdbc:postgresql://localhost:5437/team-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8086

project-service:
  url: "http://localhost:8084"
