version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - pbi-net

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_DOCKER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_HOST://localhost:9092,PLAINTEXT_DOCKER://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT_DOCKER://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_DOCKER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - pbi-net



  postgres:
    image: postgres:latest
    container_name: pbi-db
    environment:
      POSTGRES_DB: pbi-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - pbi-net

  sprint-db:
    image: postgres:latest
    container_name: sprint-db
    environment:
      POSTGRES_DB: sprint-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - sprint_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - pbi-net

  bug-db:
    image: postgres:latest
    container_name: bug-db
    environment:
      POSTGRES_DB: bug-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - bug_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - pbi-net

  feature-db:
    image: postgres:latest
    container_name: feature-db
    environment:
      POSTGRES_DB: feature-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - feature_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - pbi-net

  epic-db:
    image: postgres:latest
    container_name: epic-db
    environment:
      POSTGRES_DB: epic-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    volumes:
      - epic_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - pbi-net

  team-db:
    image: postgres:latest
    container_name: team-db
    environment:
      POSTGRES_DB: team-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5437:5432"
    volumes:
      - team_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - pbi-net

  project-db:
    image: postgres:latest
    container_name: project-db
    environment:
      POSTGRES_DB: project-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5438:5432"
    volumes:
      - team_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - pbi-net

  axonserver:
    image: axoniq/axonserver:latest
    container_name: axonserver
    ports:
      - "8124:8124"
      - "8024:8024"
    volumes:
      - axonserver-data:/axonserver/data
      - axonserver-events:/axonserver/events
      - axonserver-config:/axonserver/config
    environment:
      AXONSERVER_NAME: "axonserver-node"
      AXONSERVER_HOSTNAME: "axonserver-node"
      AXONSERVER_DEVMODE_ENABLED: "true"
    restart: unless-stopped
    networks:
      - pbi-net

volumes:
  postgres_data:
  sprint_data:
  bug_data:
  feature_data:
  team_data:
  epic_data:
  axonserver-data:
  axonserver-events:
  axonserver-config:

networks:
  pbi-net:
