spring:
  application:
    name: Bug Api
  datasource:
    url: jdbc:postgresql://localhost:5434/bug-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

axon:
  axonserver:
    enabled: true
    servers: localhost:8124