spring:
  application:
    name: Bug Api
  datasource:
    url: jdbc:postgresql://localhost:5434/bug-db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bug-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.board.bug.communication.event.FeatureCompletedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    config:
      enabled: false
axon:
  axonserver:
    enabled: true
    servers: localhost:8124

sprint-service:
  url: http://localhost:8085

feature-service:
  url: http://localhost:8082


server:
  port: 8081
